[package]
name = "trin"
version = "0.1.0"
authors = ["Jason Carver <ut96caarrs@snkmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.3"
ctrlc = "3.1.8"
lazy_static = "1.4.0"
reqwest = { version = "0.11.0", features = ["blocking"] }
serde = {version = "1.0.125", features = ["derive"] }
serde_json = "1.0.59"
threadpool = "1.8.1"
discv5 = "0.1.0-beta.3"
log = "0.4.14"
tokio = {version = "1.2.0", features = ["full"]}
futures = "0.3.13"
env_logger = "0.8.2"
uint = { version = "0.8.5", default-features = false }
eth2_ssz = "0.1.2"
eth2_ssz_derive = "0.1.0"
rlp = "0.5.0"
validator = { version = "0.13.0", features = ["derive"] }

[patch.crates-io]
discv5 = { git = "https://github.com/quilt/discv5.git", branch = "trin-quilt" }
